<?php

define("MYSQL_HOST", $_ENV['MYSQL_HOST']);
define("MYSQL_DATABASE", $_ENV['MYSQL_DATABASE']);
define("MYSQL_USER", $_ENV['MYSQL_ROOT_USER']);
define("MYSQL_PASSWORD", $_ENV['MYSQL_ROOT_PASSWORD']);
define("MYSQL_CHARSET", $_ENV["MYSQL_CHARSET"]);

define("MAX_TITLE_LENGTH", $_ENV['MAX_TITLE_LENGTH']);
define("MAX_TEXT_LENGTH", $_ENV['MAX_TEXT_LENGTH']);
define("MAX_PRICE_LENGTH", $_ENV['MAX_PRICE_LENGTH']);
define("MAX_IMAGES_COUNT", $_ENV['MAX_IMAGES_COUNT']);